# Generated by Django 4.2 on 2023-05-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('book_cover', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('isbn', models.CharField(max_length=30)),
                ('number_copies', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[(1, 'Disponível'), (2, 'Alugado'), (3, 'Reservado')], default='Disponível', max_length=20)),
            ],
        ),
    ]
