# Generated by Django 4.2 on 2023-05-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySearch', '0002_rename_author_book_autor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Livro',
        ),
    ]
