# Generated by Django 4.2 on 2023-05-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySearch', '0004_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[(1, 'Disponivel'), (2, 'Alugado'), (3, 'Reservado')], max_length=20),
        ),
    ]
